package app;

import antlr.WebTemplateLexer;
import antlr.WebTemplateParser;
import antlr.pythonLexer;
import antlr.pythonParser;
import ast.paython.ASTNode;
import ast.paython.ASTPrinter;
import ast.web.WebASTNode;
import ast.web.WebASTPrinter;
import generator.Context;
import generator.DataExtractor;
import generator.HtmlGenerator;
import generator.OutputWriter;
import org.antlr.v4.runtime.*;
import server.AppServer;
import visitor.PythonASTBuilderVisitor;
import visitor.WebASTBuilderVisitor;

import java.util.Map;

import static org.antlr.v4.runtime.CharStreams.fromFileName;

/**
 * المترجم الرئيسي — مطابق لـ:
 * - إعلان مشروع المترجمات 2025/2026
 * - رسالة الدكتورة (Code Generation: Input/Output)
 * - الملف المساعد (التحويلات الدلالية عبر HtmlGenerator)
 */
public class CompilerMain {

    public static void main(String[] args) throws Exception {

        // =====================================================
        // 1) PYTHON ANALYSIS  (ملف الدخل: app.py)
        // =====================================================
        System.out.println("===== PYTHON ANALYSIS =====");

        String pythonFile = "app.py";
        CharStream pythonInput = CharStreams.fromFileName(pythonFile);

        pythonLexer pyLexer = new pythonLexer(pythonInput);
        CommonTokenStream pyTokens = new CommonTokenStream(pyLexer);
        pyTokens.fill();

        System.out.println("tokens generated by the lexer");
        for (Token t : pyTokens.getTokens()) {
            if (t.getChannel() == Token.DEFAULT_CHANNEL) {
                String tokenName = pythonLexer.VOCABULARY.getSymbolicName(t.getType());
                System.out.printf("  %-15s -> '%s'%n",
                        tokenName,
                        t.getText().replace("\n", "\\n").replace("\r", ""));
            }
        }

        pyTokens.seek(0);
        pythonParser pyParser = new pythonParser(pyTokens);
        pythonParser.ProgContext pyTree = pyParser.prog();

        System.out.println("\n Parse Tree ");
        System.out.println(pyTree.toStringTree(pyParser));

        if (pyParser.getNumberOfSyntaxErrors() != 0) {
            System.err.println("\nPython Syntax Errors Found.");
            return;
        }
        System.out.println("successful grammatical analysis");

        PythonASTBuilderVisitor pythonVisitor = new PythonASTBuilderVisitor();
        ASTNode pythonAST = pythonVisitor.visit(pyTree);

        System.out.println("\n Abstract Syntax Tree (AST)");
        ASTPrinter.printAST(pythonAST);

        pythonVisitor.symTab.print();

        System.out.println("\n===== Flask Variables =====");
        for (String s : PythonASTBuilderVisitor.getFlaskVariables()) {
            System.out.println(s);
        }

        System.out.println("\n===== Python Semantic Errors =====");
        pythonVisitor.printsemanticErrors();

        // =====================================================
        // 2) EXTRACT DATA (Phase 6) — Context من Python AST
        // =====================================================
        DataExtractor extractor = new DataExtractor();
        Context context = extractor.extract(pythonAST);

        System.out.println("\n===== EXTRACTED DATA (Phase 6) =====");
        context.print();

        // =====================================================
        // 3) WEB / JINJA ANALYSIS  (ملفات الدخل: templates/*.jinja)
        // =====================================================
        System.out.println("\n===== WEB ANALYSIS =====");

        // القالب الرئيسي حسب رسالة الدكتورة: index.jinja
        String htmlFile = "templates/index.jinja";
        CharStream webInput = fromFileName(htmlFile);

        WebTemplateLexer webLexer = new WebTemplateLexer(webInput);
        CommonTokenStream webTokens = new CommonTokenStream(webLexer);
        webTokens.fill();

        System.out.println("Tokens generated by Web Lexer:");
        for (Token t : webTokens.getTokens()) {
            if (t.getChannel() == Token.DEFAULT_CHANNEL) {
                String tokenName = WebTemplateLexer.VOCABULARY.getSymbolicName(t.getType());
                System.out.printf("  %-20s -> '%s'%n",
                        tokenName,
                        t.getText().replace("\n", "\\n"));
            }
        }

        webTokens.seek(0);
        WebTemplateParser webParser = new WebTemplateParser(webTokens);
        WebTemplateParser.DocumentContext webTree = webParser.document();

        System.out.println("\n Web Parse Tree ");
        System.out.println(webTree.toStringTree(webParser));

        if (webParser.getNumberOfSyntaxErrors() != 0) {
            System.err.println("\nWeb Syntax Errors Found.");
            return;
        }

        WebASTBuilderVisitor webVisitor = new WebASTBuilderVisitor(
                pythonVisitor.symTab,
                PythonASTBuilderVisitor.getFlaskVariables()
        );
        WebASTNode webAST = webVisitor.visit(webTree);

        System.out.println("\n Web Abstract Syntax Tree (AST)");
        WebASTPrinter.printAST(webAST);
        webVisitor.symTab.print();

        System.out.println("\nSuccessful grammatical analysis");
        System.out.println("\n===== Web Semantic Errors =====");
        webVisitor.printSemanticErrors();

        // =====================================================
        // 4) CODE GENERATION (Phase 7)
        // Python data → Jinja AST → HTML
        // =====================================================
        System.out.println("\n===== CODE GENERATION (Phase 7) =====");

        HtmlGenerator generator = new HtmlGenerator();
        generator.setRoutes(context.getAllRoutes());

        // --- index.html (من index.jinja) ---
        // app.py يستدعي: render_template("index.html", products_list=products, title=...)
        Map<String, Object> indexData = new java.util.HashMap<>(context.getDataForTemplate("index.jinja"));
        if (!indexData.containsKey("products_list")) {
            Object products = context.getGlobalVariable("products");
            if (products != null) indexData.put("products_list", products);
        }
        if (!indexData.containsKey("title")) {
            indexData.put("title", "قائمة المنتجات");
        }
        String indexHtml = generateTemplate(
                "templates/index.jinja",
                indexData,
                pythonVisitor,
                generator
        );
        System.out.println("\n===== GENERATED: index.html =====");
        System.out.println(indexHtml);

        // --- add_product.jinja ---
        String addProductHtml = generateTemplate(
                "templates/add_product.jinja",
                context.getDataForTemplate("add_product.jinja"),
                pythonVisitor,
                generator
        );
        System.out.println("\n===== GENERATED: add_product.jinja =====");
        System.out.println(addProductHtml);

        // --- edit_product.jinja (عينة: أول منتج) ---
        Map<String, Object> editData = new java.util.HashMap<>();
        Object productsList = context.getGlobalVariable("products");
        if (productsList instanceof java.util.List && !((java.util.List<?>) productsList).isEmpty()) {
            editData.put("product", ((java.util.List<?>) productsList).get(0));
        }
        String editHtml = generateTemplate(
                "templates/edit_product.jinja",
                editData,
                pythonVisitor,
                generator
        );
        System.out.println("\n===== GENERATED: edit_product.jinja =====");
        System.out.println(editHtml);

        // --- product_details.jinja (إضافي مفيد للمشروع) ---
        Map<String, Object> detailsData = new java.util.HashMap<>();
        if (productsList instanceof java.util.List && !((java.util.List<?>) productsList).isEmpty()) {
            detailsData.put("product", ((java.util.List<?>) productsList).get(0));
        }
        String detailsHtml = generateTemplate(
                "templates/product_details.jinja",
                detailsData,
                pythonVisitor,
                generator
        );
        System.out.println("\n===== GENERATED: product_details.jinja =====");
        System.out.println(detailsHtml);

        // =====================================================
        // 5) WRITE OUTPUT FILES (Phase 8)
        // output/  +  compiler_output/  حسب رسالة الدكتورة
        // =====================================================
        System.out.println("\n===== WRITING OUTPUT FILES (Phase 8) =====");

        OutputWriter writer = new OutputWriter();
        writer.prepareDirectories();

        // الخرج المولَّد من المترجم
        writer.writeGeneratedHtml("index.html", indexHtml);
        writer.writeGeneratedHtml("add_product.html", addProductHtml);
        writer.writeGeneratedHtml("edit_product.html", editHtml);
        writer.writeGeneratedHtml("product_details.html", detailsHtml);

        // ملفات داعمة تُرفَق مع الخرج دون أي معالجة إضافية عليها (نص الدكتورة بالحرف):
        // app.py (نفس ملف الدخل كما هو) + style.css + script.js
        writer.copySupportFile("app.py", "app.py");
        writer.copySupportFile("static/style.css", "style.css");
        writer.copySupportFile("static/script.js", "script.js");

        // تقارير التحليل والتوليد
        writer.writeSemanticReport(
                pythonVisitor.getSemanticErrors(),
                webVisitor.getSemanticErrors()
        );
        writer.writePythonAstJson(pythonAST);
        writer.writeJinjaAstJson(webAST);
        writer.writeGenerationLog();

        System.out.println("\n===== DONE =====");
        System.out.println("Check folders: output/  and  compiler_output/");
        System.out.println("Generated: index.html, add_product.html, edit_product.html, product_details.html");
        System.out.println("Copied support files: app.py, style.css, script.js");

        // ==================== تشغيل السيرفر (Runtime Regeneration) ====================
        // بدل نسخ سكربت Python، الجافا نفسها بتشتغل كسيرفر runtime: بتستمع لطلبات
        // add/edit/delete وبتنادي HtmlGenerator.generate() من جديد كل مرة (نفس محرك
        // التوليد فوق) عشان يتزامن الخرج مع البيانات — تماماً متل ما وضحت الدكتورة.
        System.out.println("\n===== STARTING RUNTIME SERVER (Java) =====");
        AppServer.main(new String[0]);
    }

    /**
     * تحليل قالب Jinja واحد وتوليد HTML منه مع البيانات الممرَّرة.
     */
    private static String generateTemplate(
            String templatePath,
            Map<String, Object> data,
            PythonASTBuilderVisitor pythonVisitor,
            HtmlGenerator generator
    ) throws Exception {

        CharStream input = fromFileName(templatePath);
        WebTemplateLexer lexer = new WebTemplateLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        WebTemplateParser parser = new WebTemplateParser(tokens);
        WebTemplateParser.DocumentContext tree = parser.document();

        if (parser.getNumberOfSyntaxErrors() != 0) {
            System.err.println("Syntax errors in: " + templatePath);
            return "<!-- syntax error in " + templatePath + " -->";
        }

        WebASTBuilderVisitor visitor = new WebASTBuilderVisitor(
                pythonVisitor.symTab,
                PythonASTBuilderVisitor.getFlaskVariables()
        );
        WebASTNode ast = visitor.visit(tree);
        return generator.generate(ast, data != null ? data : new java.util.HashMap<>());
    }
}