package app;

import antlr.WebTemplateLexer;
import antlr.WebTemplateParser;
import antlr.pythonLexer;
import antlr.pythonParser;
import ast.paython.ASTNode;
import ast.paython.ASTPrinter;
import org.antlr.v4.runtime.*;
import visitor.PythonASTBuilderVisitor;
import visitor.WebASTBuilderVisitor;

import static org.antlr.v4.runtime.CharStreams.fromFileName;

public class CompilerMain {

    public static void main(String[] args) throws Exception {

        /* =====================================================
                           PYTHON ANALYSIS
        ====================================================== */
        System.out.println("===== PYTHON ANALYSIS =====");

        String pythonFile = "example/python_type_error_by_areej.py";
//        String pythonFile = "example/test.py";
        CharStream pythonInput = CharStreams.fromFileName(pythonFile);

        pythonLexer pyLexer = new pythonLexer(pythonInput);
        CommonTokenStream pyTokens = new CommonTokenStream(pyLexer);
        pyTokens.fill();

        System.out.println("tokens generated by the lexer");

        for (Token t : pyTokens.getTokens()) {
            if (t.getChannel() == Token.DEFAULT_CHANNEL) {
                String tokenName = pythonLexer.VOCABULARY.getSymbolicName(t.getType());
                // تم إضافة مسافتين في البداية لتنسيق الأكواد
                System.out.printf("  %-15s -> '%s'%n", tokenName, t.getText().replace("\n","\\n").replace("\r",""));
            }
        }

        pyTokens.seek(0);
        pythonParser pyParser = new pythonParser(pyTokens);
        pythonParser.ProgContext pyTree = pyParser.prog();

        System.out.println("\n Parse Tree ");
        System.out.println(pyTree.toStringTree(pyParser));

        if(pyParser.getNumberOfSyntaxErrors()!=0){
            System.err.println("\nPython Syntax Errors Found.");
            return;
        }

        System.out.println("successful grammatical analysis");

        PythonASTBuilderVisitor pythonVisitor = new PythonASTBuilderVisitor();
        ASTNode pythonAST = pythonVisitor.visit(pyTree);

        System.out.println("\n Abstract Syntax Tree (AST)");
        ASTPrinter.printAST(pythonAST);

       // System.out.println("\n Symbol table:\n===== SYMBOL TABLE =====");
        pythonVisitor.symTab.print();

        System.out.println("\n===== Flask Variables =====");
        for(String s : PythonASTBuilderVisitor.getFlaskVariables()){
            System.out.println(s);
        }

        System.out.println("\n===== Python Semantic Errors =====");
        pythonVisitor.printsemanticErrors();

        /* =====================================================
                             WEB ANALYSIS
        ====================================================== */
        System.out.println("\n===== WEB ANALYSIS =====");

        String htmlFile = "example/web_type_error_by_areej.html";
//        String htmlFile = "templates/products.html";
        CharStream webInput = fromFileName(htmlFile);
        WebTemplateLexer webLexer = new WebTemplateLexer(webInput);
        CommonTokenStream webTokens = new CommonTokenStream(webLexer);
        webTokens.fill();

        System.out.println("Tokens generated by Web Lexer:");

        for(Token t : webTokens.getTokens()){
            if(t.getChannel() == Token.DEFAULT_CHANNEL){
                String tokenName = WebTemplateLexer.VOCABULARY.getSymbolicName(t.getType());
                // تم إضافة مسافتين في البداية لتنسيق الأكواد
                System.out.printf("  %-20s -> '%s'%n", tokenName, t.getText().replace("\n","\\n"));
            }
        }

        webTokens.seek(0);
        WebTemplateParser webParser = new WebTemplateParser(webTokens);
        WebTemplateParser.DocumentContext webTree = webParser.document();

        if(webParser.getNumberOfSyntaxErrors() != 0){
            System.err.println("\nWeb Syntax Errors Found.");
            return;
        }

        // الأقسام الجديدة المطلوبة قبل بناء الـ Web AST
        System.out.println("TEST:");
        System.out.println(PythonASTBuilderVisitor.getFlaskVariables());
        System.out.println("===== RECEIVED FROM PYTHON =====");
        System.out.println(PythonASTBuilderVisitor.getFlaskVariables());

        WebASTBuilderVisitor webVisitor = new WebASTBuilderVisitor(
                pythonVisitor.symTab,
                PythonASTBuilderVisitor.getFlaskVariables()
        );
        webVisitor.visit(webTree);

      //  System.out.println("\n===== SYMBOL TABLE =====");
        webVisitor.symTab.print();

        System.out.println("\nSuccessful grammatical analysis");

        System.out.println("\n===== Web Semantic Errors =====");
        webVisitor.printSemanticErrors();
    }
}