package app;

import antlr.WebTemplateLexer;
import antlr.WebTemplateParser;
import antlr.pythonLexer;
import antlr.pythonParser;
import ast.paython.ASTNode;
import ast.paython.ASTPrinter;
import ast.web.WebASTNode;
import ast.web.WebASTPrinter;
import generator.Context;
import generator.DataExtractor;
import generator.HtmlGenerator;
import generator.OutputWriter;
import org.antlr.v4.runtime.*;
import server.AppServer;
import visitor.PythonASTBuilderVisitor;
import visitor.WebASTBuilderVisitor;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.antlr.v4.runtime.CharStreams.fromFileName;

/**
 * المترجم الرئيسي — مطابق لـ:
 * - إعلان مشروع المترجمات 2025/2026
 * - رسالة الدكتورة (Code Generation: Input/Output)
 * - الملف المساعد (التحويلات الدلالية عبر HtmlGenerator)
 *
 * سياسة معالجة الأخطاء الدلالية (متفق عليها):
 * 1) يتم تشغيل الـ Semantic Analysis بالكامل (Python + Web/Jinja) دون توقف عند أول خطأ.
 * 2) تُكتب كل الأخطاء المُجمَّعة إلى compiler_output/semantic_report.txt دائماً.
 * 3) إذا وُجد أي خطأ دلالي (Python أو Web) => يتوقف التوليد بالكامل، ولا تُنتَج
 *    ملفات output/ (لا HTML ولا نسخ للملفات الداعمة)، ويُسجَّل السبب في generation_log.txt.
 * 4) فقط إذا كانت قائمة الأخطاء فاضية بالكامل => تُنفَّذ مرحلة الـ Generation الحقيقية.
 */
public class CompilerMain {

    public static void main(String[] args) throws Exception {

        OutputWriter writer = new OutputWriter();
        writer.prepareDirectories(); // ننشئ output/ و compiler_output/ من البداية

        // =====================================================
        // 1) PYTHON ANALYSIS  (ملف الدخل: app.py)
        // =====================================================
        System.out.println("===== PYTHON ANALYSIS =====");

       String pythonFile = "example/semantic_errors_python.py";
//        String pythonFile = "app.py";

        CharStream pythonInput = CharStreams.fromFileName(pythonFile);

        pythonLexer pyLexer = new pythonLexer(pythonInput);
        CommonTokenStream pyTokens = new CommonTokenStream(pyLexer);
        pyTokens.fill();

        System.out.println("tokens generated by the lexer");
        for (Token t : pyTokens.getTokens()) {
            if (t.getChannel() == Token.DEFAULT_CHANNEL) {
                String tokenName = pythonLexer.VOCABULARY.getSymbolicName(t.getType());
                System.out.printf("  %-15s -> '%s'%n",
                        tokenName,
                        t.getText().replace("\n", "\\n").replace("\r", ""));
            }
        }

        pyTokens.seek(0);
        pythonParser pyParser = new pythonParser(pyTokens);
        pythonParser.ProgContext pyTree = pyParser.prog();

        System.out.println("\n Parse Tree ");
        System.out.println(pyTree.toStringTree(pyParser));

        if (pyParser.getNumberOfSyntaxErrors() != 0) {
            // خطأ نحوي: لا يمكن بناء AST سليم => توقف فوري (لا يوجد بديل هنا كما بالمترجمات الحقيقية)
            System.err.println("\nPython Syntax Errors Found.");
            writer.writeSyntaxErrorReport("Python", "Number of syntax errors: " + pyParser.getNumberOfSyntaxErrors());
            writer.logGenerationAbortedSyntax("Python");
            writer.writeGenerationLog();
            return;
        }
        System.out.println("successful grammatical analysis");

        PythonASTBuilderVisitor pythonVisitor = new PythonASTBuilderVisitor();
        ASTNode pythonAST = pythonVisitor.visit(pyTree);

        System.out.println("\n Abstract Syntax Tree (AST)");
        ASTPrinter.printAST(pythonAST);

        pythonVisitor.symTab.print();

        System.out.println("\n===== Flask Variables =====");
        for (String s : PythonASTBuilderVisitor.getFlaskVariables()) {
            System.out.println(s);
        }

        System.out.println("\n===== Python Semantic Errors =====");
        pythonVisitor.printsemanticErrors();
        // ملاحظة: ما منعمل return هون. منجمع الأخطاء ومنكمل لتحليل الـ Web
        // عشان نطبع كل الأخطاء (Python + Web) دفعة وحدة بالتقرير النهائي.

        // نكتب ast_python.json دائماً، لأن الـ AST اتبنى بنجاح بغض النظر عن الأخطاء الدلالية
        writer.writePythonAstJson(pythonAST);

        // =====================================================
        // 2) WEB / JINJA ANALYSIS  (ملفات الدخل: templates/*.jinja)
        // =====================================================
        System.out.println("\n===== WEB ANALYSIS =====");

        String htmlFile = "templates/index.jinja";
        CharStream webInput = fromFileName(htmlFile);

        WebTemplateLexer webLexer = new WebTemplateLexer(webInput);
        CommonTokenStream webTokens = new CommonTokenStream(webLexer);
        webTokens.fill();

        System.out.println("Tokens generated by Web Lexer:");
        for (Token t : webTokens.getTokens()) {
            if (t.getChannel() == Token.DEFAULT_CHANNEL) {
                String tokenName = WebTemplateLexer.VOCABULARY.getSymbolicName(t.getType());
                System.out.printf("  %-20s -> '%s'%n",
                        tokenName,
                        t.getText().replace("\n", "\\n"));
            }
        }

        webTokens.seek(0);
        WebTemplateParser webParser = new WebTemplateParser(webTokens);
        WebTemplateParser.DocumentContext webTree = webParser.document();

        System.out.println("\n Web Parse Tree ");
        System.out.println(webTree.toStringTree(webParser));

        WebASTNode webAST = null;
        List<String> webErrors = new ArrayList<>();

        if (webParser.getNumberOfSyntaxErrors() != 0) {
            // نفس منطق الـ Python: خطأ نحوي بالـ Jinja يمنع بناء AST سليم => توقف فوري
            System.err.println("\nWeb Syntax Errors Found.");
            writer.writeSyntaxErrorReport("Web/Jinja", "Number of syntax errors: " + webParser.getNumberOfSyntaxErrors());
            writer.logGenerationAbortedSyntax("Web/Jinja");
            writer.writeGenerationLog();
            return;
        }

        WebASTBuilderVisitor webVisitor = new WebASTBuilderVisitor(
                pythonVisitor.symTab,
                PythonASTBuilderVisitor.getFlaskVariables()
        );
        webAST = webVisitor.visit(webTree);

        System.out.println("\n Web Abstract Syntax Tree (AST)");
        WebASTPrinter.printAST(webAST);
        webVisitor.symTab.print();

        System.out.println("\nSuccessful grammatical analysis");
        System.out.println("\n===== Web Semantic Errors =====");
        webVisitor.printSemanticErrors();
        webErrors = webVisitor.getSemanticErrors();

        // نكتب ast_jinja.json دائماً أيضاً، بنفس منطق ast_python.json
        writer.writeJinjaAstJson(webAST);

        // =====================================================
        // 3) SEMANTIC REPORT — تُكتب دائماً بغض النظر عن النتيجة
        // =====================================================
        List<String> pythonErrors = pythonVisitor.getSemanticErrors();
        writer.writeSemanticReport(pythonErrors, webErrors);

        int totalErrors = pythonErrors.size() + webErrors.size();

        // =====================================================
        // 4) الـ GATE: قرار المتابعة للتوليد أو التوقف
        // =====================================================
        if (totalErrors > 0) {
            System.err.println("\n Semantic Errors Found (" + totalErrors + ") — Code Generation Aborted.");
            System.err.println("See compiler_output/semantic_report.txt for details.");
            writer.logGenerationAborted(pythonErrors.size(), webErrors.size());
            writer.writeGenerationLog();
            System.out.println("\n===== DONE (ABORTED) =====");
            System.out.println("Check compiler_output/ for semantic_report.txt and generation_log.txt");
            return; // لا يوجد أي إنتاج لملفات output/ إطلاقاً، ولا تشغيل للسيرفر
        }

        // =====================================================
        // 5) EXTRACT DATA (Phase 6) — Context من Python AST
        //    (ما بتنفّذ إلا إذا ما في ولا خطأ دلالي واحد)
        // =====================================================
        DataExtractor extractor = new DataExtractor();
        Context context = extractor.extract(pythonAST);

        System.out.println("\n===== EXTRACTED DATA (Phase 6) =====");
        context.print();

        // =====================================================
        // 6) CODE GENERATION (Phase 7)
        // Python data → Jinja AST → HTML
        // =====================================================
        System.out.println("\n===== CODE GENERATION (Phase 7) =====");

        HtmlGenerator generator = new HtmlGenerator();
        generator.setRoutes(context.getAllRoutes());

        // --- index.html (من index.jinja) ---
        Map<String, Object> indexData = new java.util.HashMap<>(context.getDataForTemplate("index.jinja"));
        if (!indexData.containsKey("products_list")) {
            Object products = context.getGlobalVariable("products");
            if (products != null) indexData.put("products_list", products);
        }
        if (!indexData.containsKey("title")) {
            indexData.put("title", "قائمة المنتجات");
        }
        String indexHtml = generateTemplate(
                "templates/index.jinja",
                indexData,
                pythonVisitor,
                generator
        );
        System.out.println("\n===== GENERATED: index.html =====");
        System.out.println(indexHtml);

        // --- add_product.jinja ---
        String addProductHtml = generateTemplate(
                "templates/add_product.jinja",
                context.getDataForTemplate("add_product.jinja"),
                pythonVisitor,
                generator
        );
        System.out.println("\n===== GENERATED: add_product.jinja =====");
        System.out.println(addProductHtml);

        // --- edit_product.jinja (عينة: أول منتج) ---
        Map<String, Object> editData = new java.util.HashMap<>();
        Object productsList = context.getGlobalVariable("products");
        if (productsList instanceof java.util.List && !((java.util.List<?>) productsList).isEmpty()) {
            editData.put("product", ((java.util.List<?>) productsList).get(0));
        }
        String editHtml = generateTemplate(
                "templates/edit_product.jinja",
                editData,
                pythonVisitor,
                generator
        );
        System.out.println("\n===== GENERATED: edit_product.jinja =====");
        System.out.println(editHtml);

        // --- product_details.jinja ---
        Map<String, Object> detailsData = new java.util.HashMap<>();
        if (productsList instanceof java.util.List && !((java.util.List<?>) productsList).isEmpty()) {
            detailsData.put("product", ((java.util.List<?>) productsList).get(0));
        }
        String detailsHtml = generateTemplate(
                "templates/product_details.jinja",
                detailsData,
                pythonVisitor,
                generator
        );
        System.out.println("\n===== GENERATED: product_details.jinja =====");
        System.out.println(detailsHtml);

        // =====================================================
        // 7) WRITE OUTPUT FILES (Phase 8)
        // =====================================================
        System.out.println("\n===== WRITING OUTPUT FILES (Phase 8) =====");

        writer.writeGeneratedHtml("index.html", indexHtml);
        writer.writeGeneratedHtml("add_product.html", addProductHtml);
        writer.writeGeneratedHtml("edit_product.html", editHtml);
        writer.writeGeneratedHtml("product_details.html", detailsHtml);

        writer.copySupportFile("app.py", "app.py");
        writer.copySupportFile("static/style.css", "style.css");


        writer.logGenerationSucceeded();
        writer.writeGenerationLog();

        System.out.println("\n===== DONE =====");
        System.out.println("Check folders: output/  and  compiler_output/");
        System.out.println("Generated: index.html, add_product.html, edit_product.html, product_details.html");
        System.out.println("Copied support files: app.py, style.css");

        // ==================== تشغيل السيرفر (Runtime Regeneration) ====================
        System.out.println("\n===== STARTING RUNTIME SERVER (Java) =====");
        AppServer.main(new String[]{ pythonFile });
    }

    /**
     * تحليل قالب Jinja واحد وتوليد HTML منه مع البيانات الممرَّرة.
     */
    private static String generateTemplate(
            String templatePath,
            Map<String, Object> data,
            PythonASTBuilderVisitor pythonVisitor,
            HtmlGenerator generator
    ) throws Exception {

        CharStream input = fromFileName(templatePath);
        WebTemplateLexer lexer = new WebTemplateLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        WebTemplateParser parser = new WebTemplateParser(tokens);
        WebTemplateParser.DocumentContext tree = parser.document();

        if (parser.getNumberOfSyntaxErrors() != 0) {
            System.err.println("Syntax errors in: " + templatePath);
            return "<!-- syntax error in " + templatePath + " -->";
        }

        WebASTBuilderVisitor visitor = new WebASTBuilderVisitor(
                pythonVisitor.symTab,
                PythonASTBuilderVisitor.getFlaskVariables()
        );
        WebASTNode ast = visitor.visit(tree);
        return generator.generate(ast, data != null ? data : new java.util.HashMap<>());
    }
}