package app;
import antlr.pythonLexer;
import antlr.pythonParser;
import ast.paython.ASTNode;
import ast.paython.ASTPrinter;
import org.antlr.v4.runtime.*;
import visitor.PythonASTBuilderVisitor;

import java.io.IOException;

public class PythonMain {

    public static void main(String[] args) throws Exception {
    try{
        String filePath = "example/python_test.py";
        CharStream input = CharStreams.fromFileName(filePath);

        pythonLexer lexer = new pythonLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        tokens.fill();

        System.out.println("tokens generated by the lexer");
        for (Token t : tokens.getTokens()) {
            if (t.getChannel() == Token.DEFAULT_CHANNEL) {
                String tokenName =
                        pythonLexer.VOCABULARY.getSymbolicName(t.getType());
                System.out.printf(
                        "  %-10s -> '%s'\n", tokenName,
                        t.getText().replace("\n", "\\n").replace("\r", "")
                );
            }
        }
        tokens.seek(0);
        pythonParser parser = new pythonParser(tokens);
        pythonParser.ProgContext tree = parser.prog();

        System.out.println("\n Parse Tree ");
        System.out.println(tree.toStringTree(parser));

        if (parser.getNumberOfSyntaxErrors() == 0) {
            System.out.println("\n successful grammatical analysis");
        } else {
            System.err.println("\n failure of grammatical analysis");
            return;
        }
        PythonASTBuilderVisitor visitor = new PythonASTBuilderVisitor();
        ASTNode astRoot = visitor.visit(tree);

      System.out.println("\n Abstract Syntax Tree (AST)");
      ASTPrinter.printAST(astRoot);
        System.out.println("\n Symbol table:");
        visitor.symTab.print();
    }
    catch (IOException e) {
        e.printStackTrace();
    }
    }

}
