package app;


import antlr.WebTemplateLexer;
import antlr.WebTemplateParser;
import ast.web.WebASTNode;
import org.antlr.v4.runtime.*;
import visitor.WebASTBuilderVisitor;



public class WebMain {

    public static void main(String[] args) throws Exception {

     String filePath = "example/web.html";
//         String filePath = "example/add_product.html";
//          String filePath = "example/product_details.html";
//            String filePath = "example/products.html";
        CharStream input = CharStreams.fromFileName(filePath);

        WebTemplateLexer lexer = new WebTemplateLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        tokens.fill();

        System.out.println("Tokens generated by Web Lexer:");
        for (Token t : tokens.getTokens()) {
            if (t.getChannel() == Token.DEFAULT_CHANNEL) {
                String tokenName =
                        WebTemplateLexer.VOCABULARY.getSymbolicName(t.getType());
                System.out.printf(
                        "  %-20s -> '%s'\n",
                        tokenName,
                        t.getText().replace("\n", "\\n")
                );
            }
        }

        tokens.seek(0);
        WebTemplateParser parser = new WebTemplateParser(tokens);
        WebTemplateParser.DocumentContext tree = parser.document();

        System.out.println("\nParse Tree:");
        System.out.println(tree.toStringTree(parser));

        if (parser.getNumberOfSyntaxErrors() == 0) {
            System.out.println("\nSuccessful grammatical analysis");
        } else {
            System.err.println("\nSyntax errors found");
            return;
        }

        WebASTBuilderVisitor visitor = new WebASTBuilderVisitor();
        WebASTNode astRoot = visitor.visit(tree);

        System.out.println("\nAbstract Syntax Tree (Web AST):");
        astRoot.print("");

        System.out.println("\n Symbol table:");
        visitor.symTab.print();
    }
}