package app;

import antlr.WebTemplateLexer;
import antlr.WebTemplateParser;
import org.antlr.v4.runtime.*;

import static org.antlr.v4.runtime.CharStreams.*;

public class WebMain {

    public static void main(String[] args) throws Exception {

        String filePath = "templates/products.html";
//        String filePath = "templates/add_product.html";
//        String filePath = "templates/product_details.html";
//        String filePath = "example/test.html";

        CharStream input = fromFileName(filePath);

        WebTemplateLexer lexer = new WebTemplateLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);

        tokens.fill();

        System.out.println("Tokens generated by Web Lexer:");

        for (Token t : tokens.getTokens()) {
            if (t.getChannel() == Token.DEFAULT_CHANNEL) {
                String tokenName =
                        WebTemplateLexer.VOCABULARY.getSymbolicName(t.getType());

                System.out.printf(
                        "  %-20s -> '%s'%n",
                        tokenName,
                        t.getText().replace("\n", "\\n")
                );
            }
        }

        tokens.seek(0);

        WebTemplateParser parser = new WebTemplateParser(tokens);

        // ✅ FIX: entry point is document not template
        WebTemplateParser.DocumentContext tree = parser.document();

        System.out.println("\nParse Tree:");
        System.out.println(tree.toStringTree(parser));

        if (parser.getNumberOfSyntaxErrors() == 0) {
            System.out.println("\nSuccessful grammatical analysis");
        } else {
            System.err.println("\nSyntax errors found");
        }
    }
}