//package app;
//
//import antlr.WebTemplateLexer;
//import antlr.WebTemplateParser;
//import org.antlr.v4.runtime.*;
//import visitor.PythonASTBuilderVisitor;
//import visitor.WebASTBuilderVisitor;
//import static org.antlr.v4.runtime.CharStreams.*;
//
//public class WebMain {
//    public static void main(String[] args) throws Exception {
//        String filePath = "templates/products.html";
////        String filePath = "example/web_type_error_by_areej.html";
//        CharStream input = fromFileName(filePath);
//
//        WebTemplateLexer lexer = new WebTemplateLexer(input);
//        CommonTokenStream tokens = new CommonTokenStream(lexer);
//        tokens.fill();
//
//        System.out.println("Tokens generated by Web Lexer:");
//        for (Token t : tokens.getTokens()) {
//            if (t.getChannel() == Token.DEFAULT_CHANNEL) {
//                String tokenName = WebTemplateLexer.VOCABULARY.getSymbolicName(t.getType());
//                System.out.printf("  %-20s -> '%s'%n", tokenName, t.getText().replace("\n", "\\n"));
//            }
//        }
//
//        tokens.seek(0);
//        WebTemplateParser parser = new WebTemplateParser(tokens);
//        WebTemplateParser.DocumentContext tree = parser.document();
//
//        if (parser.getNumberOfSyntaxErrors() == 0) {
//            System.out.println("TEST:");
//            System.out.println(PythonASTBuilderVisitor.getFlaskVariables());
//
//            WebASTBuilderVisitor visitor =
//                    new WebASTBuilderVisitor(
//                            pythonVisitor.symTab,
//                            PythonASTBuilderVisitor.getFlaskVariables()
//                    );
//            visitor.visit(tree);
//            visitor.symTab.print();
//
//            // ✅ طباعة الأخطاء في النهاية
//            System.out.println("\n===== WEB SEMANTIC ERRORS =====");
//            visitor.printSemanticErrors();
//
//            System.out.println("\nSuccessful grammatical analysis");
//        } else {
//            System.err.println("\nSyntax errors found");
//        }
//    }
//}